//import { TreeNode } from "./tree-node";

//export const TREEDATA: TreeNode = {
//    "issueId": 1,
//    "issueTitle": "Add video upload function",
//    "projectTitle": "",
//    "issueDescription": "",
//    "priorityName": "",
//    "statusName": "",
//    "priorityImage":"",
//    "typeName": "",
//    "x0": null,
//    "y0": null,
//    "x": null,
//    "y": null,
//    "userAvatarPath": "http://img.photobucket.com/albums/v490/Poopenstance/catwithtie.gif",
//    "userName": "Kevin Bacon",
//    "statusCatColor": "blue",
//    "statusCatName": "Staging",
//    "dependentOn": null,
//    "tempChildren": [],
//    "children": [
//        {
//            "issueId": 2,
//            "issueTitle": "Add video upload function",
//            "projectTitle": "",
//            "issueDescription": "",
//            "priorityName": "",
//            "priorityImage":"",
//            "statusName": "",
//            "typeName":"",
//            "x0": null,
//            "y0": null,
//            "x": null,
//            "y": null,
//            "userAvatarPath": "http://img.photobucket.com/albums/v490/Poopenstance/catwithtie.gif",
//            "userName": "Sara Blue",
//            "statusCatColor": "green",
//            "statusCatName": "Staging",
//            "dependentOn": 1,
//            "tempChildren": [],
//            "children": [
//                {
//                    "issueId": 6,
//                    "issueTitle": "Add video upload function",
//                    "projectTitle": "",
//                    "issueDescription": "",
//                    "priorityName": "",
//                    "priorityImage":"",
//                    "statusName": "",
//                    "typeName": "",
//                    "x0": null,
//                    "y0": null,
//                    "x": null,
//                    "y": null,
//                    "userAvatarPath": "http://img.photobucket.com/albums/v490/Poopenstance/catwithtie.gif",
//                    "userName": "Kyle Stevens",
//                    "statusCatColor": "red",
//                    "statusCatName": "Staging",
//                    "dependentOn": 2,
//                    "tempChildren": [],
//                    "children": []
//                },
//                {
//                    "issueId": 7,
//                    "issueTitle": "Add video upload function",
//                    "projectTitle": "",
//                    "issueDescription": "",
//                    "priorityName": "",
//                    "priorityImage":"",
//                    "statusName": "",
//                    "typeName": "",
//                    "x0": null,
//                    "y0": null,
//                    "x": null,
//                    "y": null,
//                    "userAvatarPath": "http://img.photobucket.com/albums/v490/Poopenstance/catwithtie.gif",
//                    "userName": "Matt Rogers",
//                    "statusCatColor": "red",
//                    "statusCatName": "Staging",
//                    "dependentOn": 2,
//                    "tempChildren": [],
//                    "children": []
//                }
//            ]
//        },
//        {
//            "issueId": 3,
//            "issueTitle": "Add video upload function",
//            "projectTitle": "",
//            "issueDescription": "",
//            "priorityName": "",
//            "statusName": "",
//            "typeName": "",
//            "x0": null,
//            "y0": null,
//            "x": null,
//            "y": null,
//            "userAvatarPath": "http://img.photobucket.com/albums/v490/Poopenstance/catwithtie.gif",
//            "userName": "Tom Miles",
//            "statusCatColor": "green",
//            "statusCatName": "Staging",
//            "dependentOn": 1,
//            "tempChildren": [],
//            "children": [
//                {
//                    "issueId": 4,
//                    "issueTitle": "Add video upload function",
//                    "projectTitle": "",
//                    "issueDescription": "",
//                    "priorityName": "",
//                    "statusName": "",
//                    "typeName":"",
//                    "x0": null,
//                    "y0": null,
//                    "x": null,
//                    "y": null,
//                    "userAvatarPath": "http://img.photobucket.com/albums/v490/Poopenstance/catwithtie.gif",
//                    "userName": "Kyle Stevens",
//                    "statusCatColor": "red",
//                    "statusCatName": "Staging",
//                    "dependentOn": 3,
//                    "tempChildren": [],
//                    "children": []
//                },
//                {
//                    "issueId": 5,
//                    "issueTitle": "Add video upload function",
//                    "projectTitle": "",
//                    "issueDescription": "",
//                    "priorityName": "",
//                    "statusName": "",
//                    "typeName": "",
//                    "x0": null,
//                    "y0": null,
//                    "x": null,
//                    "y": null,
//                    "userAvatarPath": "http://img.photobucket.com/albums/v490/Poopenstance/catwithtie.gif",
//                    "userName": "Matt Rogers",
//                    "statusCatColor": "red",
//                    "statusCatName": "Staging",
//                    "dependentOn": 3,
//                    "tempChildren": [],
//                    "children": []
//                }
//            ]
//        }
//    ]
//};